name: example
logpath: ./onerpc.log
registry:
  etcd:
    endpoints: ["http://127.0.0.2:5101", "http://127.0.0.1:5103"]
    dial_timeout: 5
    dial_keepalive_time: 3
    lease_ttl: 60
server:
  alpha:
    address: 127.0.0.1:5000
    protocol: tcp
    max_invoke: 300
    queue_cap: 200
    accept_timeout: 3000
    read_timeout: 3000
    write_timeout: 3000
    handle_timeout: 3000
    idle_timeout: 3000
    tcp_read_buf: 4194304
    tcp_write_buf: 4194304
    tcp_nodelay: false

client:
  balance: normal
  trans_protocol: tcp
  queue_cap: 10000
  dial_timeout: 3000
  read_timeout: 3000
  write_timeout: 3000
  idle_timeout: 3000