// Code generated by protoc-gen-go. DO NOT EDIT.
// source: endpointf/endpointf.proto

package endpointf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EndpointF struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EndpointF) Reset()         { *m = EndpointF{} }
func (m *EndpointF) String() string { return proto.CompactTextString(m) }
func (*EndpointF) ProtoMessage()    {}
func (*EndpointF) Descriptor() ([]byte, []int) {
	return fileDescriptor_2df866744f673f5e, []int{0}
}

func (m *EndpointF) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndpointF.Unmarshal(m, b)
}
func (m *EndpointF) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndpointF.Marshal(b, m, deterministic)
}
func (m *EndpointF) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndpointF.Merge(m, src)
}
func (m *EndpointF) XXX_Size() int {
	return xxx_messageInfo_EndpointF.Size(m)
}
func (m *EndpointF) XXX_DiscardUnknown() {
	xxx_messageInfo_EndpointF.DiscardUnknown(m)
}

var xxx_messageInfo_EndpointF proto.InternalMessageInfo

func (m *EndpointF) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func init() {
	proto.RegisterType((*EndpointF)(nil), "endpointf.EndpointF")
}

func init() { proto.RegisterFile("endpointf/endpointf.proto", fileDescriptor_2df866744f673f5e) }

var fileDescriptor_2df866744f673f5e = []byte{
	// 77 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4c, 0xcd, 0x4b, 0x29,
	0xc8, 0xcf, 0xcc, 0x2b, 0x49, 0xd3, 0x87, 0xb3, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x38,
	0xe1, 0x02, 0x4a, 0xf2, 0x5c, 0x9c, 0xae, 0x50, 0x8e, 0x9b, 0x90, 0x10, 0x17, 0x4b, 0x72, 0x7e,
	0x4a, 0xaa, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x6b, 0x10, 0x98, 0x9d, 0xc4, 0x06, 0xd6, 0x62, 0x0c,
	0x08, 0x00, 0x00, 0xff, 0xff, 0x70, 0x3d, 0x99, 0x0e, 0x4f, 0x00, 0x00, 0x00,
}

// fffffffffffffffff
